name: dnaio-benchmark-comparison
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10  # Update to 3.11 once released
  - tox
  - fastp  # Cannot be installed by tox. The bioconda version is build with isa-l and libdeflate.
