name: dnaio-benchmark-comparison
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10  # Update to 3.11 once released
  - tox
  # Dependencies for fastp
  - isa-l
  - libdeflate
